### ISSUE TITLE
Error in Comparing netCDF files

### ISSUE THREAD

**Issue by Ahmadffrahmand** [c-h-david/shbaam#10]
Respected Sir,
I am running SHBAAM tsts for RL06 mascon v02, the code downloaded the data perfectly the test for concatenation also executed with out problem. 

but for comparing two netcdf file i am getting this error.  

Comparing netCDF files
1st netCDF file               :../output/SERVIR_STK/GLDAS_CLM10_M.A200204_201701.nc
2nd netCDF file               :../output/SERVIR_STK/GLDAS_CLM10_M.A200204_201701_tst.nc
Relative tolerance            :1e-06
Absolute tolerance            :1e-06
-------------------------------
ERROR - Neither lon nor Lon are dimensions in: ../output/SERVIR_STK/GLDAS_CLM10_M.A200204_201701.nc

With best regards
Ahmad

**Comment by c-h-david** [comment]
Hi Ahmad, I don't know how you generated your file `GLDAS_CLM10_M.A200204_201701.nc` but it looks like it does not have a dimension for longitude. This should not be the case if you've used `shbaam_conc.py` to generate it. That's what this error is about.
